import Head from "next/head";
import React, { useState } from "react";
import Teams from "../components/Teams";
import styles from "../../styles/Home.module.css";
import Squads from "../components/Squads";

export default function Home() {
  const [teams, setTeams] = useState([]);
  const [squads, setSquads] = useState({});
  const [player, setPlayer] = useState("Player Name");
  const [squad, setSquad] = useState("9a7059e278");
  const [loading, setLoading] = useState(false);

  const loadSquad = async () => {
    setLoading(true);
    const req = await fetch(`/api/squad/${squad}`);
    const json = await req.json();
    setSquads(json);
    setLoading(false);
  };

  const loadPeople = async () => {
    setLoading(true);
    const req = await fetch(`/api/player/${player}`);
    const json = await req.json();
    setTeams(json);
    setLoading(false);
  };

  return (
    <div className={styles.main}>
      <Head>
        <title>Liam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Silph Team Finder</h1>
        <br />
        <div>
          <select
            value={squad}
            onChange={(e) => setSquad(e.currentTarget.value)}
          >
            <option value="9a7059e278">Stoked</option>
          </select>
          <button onClick={() => loadSquad()}>Load</button>

          <input value={player} onChange={(e) => setPlayer(e.target.value)} />
          <button onClick={() => loadPeople()}>Load</button>
          {loading && <div className={styles.load}>LOADING</div>}
        </div>
        <div className={styles.teams}>
          <Squads squad={squads} />

          <Teams teams={teams} />
        </div>
      </main>
    </div>
  );
}
